# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 02:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=512, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_() .]+$', 32), 'Use ASCII characters only')], verbose_name='Software name')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
