# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
